LANGUAGES = [
    ('en', 'English'),
    ('af', 'Afrikaans'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('hy', 'Armenian'),
    ('bn', 'Bengali'),
    ('bs', 'Bosnian'),
    ('ca', 'Catalan'),
    ('hr', 'Croatian'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('nl', 'Dutch'),
    ('en-gb', 'British English'),
    ('eo', 'Esperanto'),
    ('et', 'Estonian'),
    ('tl', 'Filipino'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('el', 'Greek'),
    ('gu', 'Gujarati'),
    ('hi', 'Hindi'),
    ('hu', 'Hungarian'),
    ('is', 'Icelandic'),
    ('id', 'Indonesian'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('jw', 'Javanese'),
    ('ka', 'Georgian'),
    ('km', 'Khmer'),
    ('ko', 'Korean'),
    ('la', 'Latin'),
    ('lv', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('mk', 'Macedonian'),
    ('ml', 'Malayalam'),
    ('mr', 'Marathi'),
    ('my', 'Burmese'),
    ('ne', 'Nepali'),
    ('no', 'Norwegian'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese'),
    ('pa', 'Punjabi'),
    ('ro', 'Romanian'),
    ('ru', 'Russian'),
    ('sr', 'Serbian'),
    ('si', 'Sinhala'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('es', 'Spanish'),
    ('su', 'Sundanese'),
    ('sw', 'Swahili'),
    ('sv', 'Swedish'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('th', 'Thai'),
    ('tr', 'Turkish'),
    ('uk', 'Ukrainian'),
    ('ur', 'Urdu'),
    ('vi', 'Vietnamese'),
    ('cy', 'Welsh'),
    ('xh', 'Xhosa'),
    ('yi', 'Yiddish'),
    ('zu', 'Zulu'),
    ('gl', 'Galician'),
    ('gu', 'Gujarati'),
    ('or', 'Odia'),
    ('pa', 'Punjabi'),
    ('mr', 'Marathi'),
    ('ne', 'Nepali'),
    ('ta', 'Tamil'),
    ('te', 'Telugu'),
    ('bn', 'Bengali'),
    ('hi', 'Hindi'),
    ('jv', 'Javanese'),
    ('da', 'Danish'),
    ('no', 'Norwegian'),
    ('fi', 'Finnish'),
    ('es-mx', 'Mexican Spanish'),
    ('pt-br', 'Brazilian Portuguese'),
    ('sr-latn', 'Serbian (Latin)'),
    ('bs-latn', 'Bosnian (Latin)'),
    ('cy-gb', 'Welsh (GB)'),
    ('ml', 'Malayalam'),
    ('gu', 'Gujarati'),
    ('pa', 'Punjabi'),
    ('mr', 'Marathi'),
    ('sw-ke', 'Swahili (Kenya)'),
    ('ta-lk', 'Tamil (Sri Lanka)'),
    ('es-ar', 'Argentinian Spanish'),
    ('it-ch', 'Swiss Italian'),
    ('fr-ca', 'Canadian French'),
    ('nl-be', 'Belgian Dutch'),
    ('pl-pl', 'Polish (Poland)'),
    ('bs-ba', 'Bosnian (Bosnia and Herzegovina)'),
    ('sr-rs', 'Serbian (Serbia)'),
    ('te', 'Telugu'),
    ('ml', 'Malayalam'),
    ('hr', 'Croatian'),
    ('lv', 'Latvian'),
    ('sl', 'Slovenian'),
    ('et', 'Estonian'),
    ('bg', 'Bulgarian'),
    ('ar-sa', 'Arabic (Saudi Arabia)'),
    ('fa-ir', 'Persian (Iran)'),
    ('iw', 'Hebrew'),
    ('nep', 'Nepali'),
    ('pt-pt', 'Portuguese (Portugal)'),
    ('tl-ph', 'Filipino (Philippines)'),
    ('hu', 'Hungarian'),
    ('cs', 'Czech'),
    ('uk-ua', 'Ukrainian'),
    ('bs-me', 'Bosnian (Montenegro)'),
    ('mr', 'Marathi'),
    ('sr', 'Serbian'),
    ('id-id', 'Indonesian (Indonesia)'),
    ('sq-al', 'Albanian (Albania)'),
    ('mk', 'Macedonian'),
    ('cy', 'Welsh'),
    ('oc', 'Occitan'),
    ('hu-hu', 'Hungarian (Hungary)'),
    ('eu', 'Basque'),
    ('zu', 'Zulu'),
    ('si', 'Sinhala'),
    ('az', 'Azerbaijani'),
    ('bn-bd', 'Bengali (Bangladesh)'),
    ('km-kh', 'Khmer (Cambodia)'),
    ('ne-np', 'Nepali (Nepal)'),
    ('si-lk', 'Sinhala (Sri Lanka)'),
    ('tr-tr', 'Turkish'),
    ('vi-vn', 'Vietnamese'),
    ('ro-ro', 'Romanian'),
    ('zh-cn', 'Chinese (China)'),
    ('zh-tw', 'Chinese (Taiwan)'),
    ('bn-IN', 'Bengali (India)'),
    ('en-au', 'English (Australia)'),
    ('sw-tz', 'Swahili (Tanzania)'),
    ('es-cl', 'Spanish (Chile)'),
    ('fr-be', 'French (Belgium)'),
    ('nl-nl', 'Dutch (Netherlands)'),
    ('pl-pl', 'Polish (Poland)'),
    ('uk-ua', 'Ukrainian (Ukraine)'),
    ('es-co', 'Spanish (Colombia)'),
    ('pt-mo', 'Portuguese (Macau)'),
    ('en-ca', 'English (Canada)'),
]
