from django.utils.translation import gettext_lazy as _

languages = [
    ('en', _('English')),
    ('af', _('Afrikaans')),
    ('sq', _('Albanian')),
    ('am', _('Amharic')),
    ('ar', _('Arabic')),
    ('hy', _('Armenian')),
    ('bn', _('Bengali')),
    ('bs', _('Bosnian')),
    ('ca', _('Catalan')),
    ('hr', _('Croatian')),
    ('cs', _('Czech')),
    ('da', _('Danish')),
    ('nl', _('Dutch')),
    ('en-gb', _('British English')),
    ('eo', _('Esperanto')),
    ('et', _('Estonian')),
    ('tl', _('Filipino')),
    ('fi', _('Finnish')),
    ('fr', _('French')),
    ('de', _('German')),
    ('el', _('Greek')),
    ('gu', _('Gujarati')),
    ('hi', _('Hindi')),
    ('hu', _('Hungarian')),
    ('is', _('Icelandic')),
    ('id', _('Indonesian')),
    ('it', _('Italian')),
    ('ja', _('Japanese')),
    ('jw', _('Javanese')),
    ('ka', _('Georgian')),
    ('km', _('Khmer')),
    ('ko', _('Korean')),
    ('la', _('Latin')),
    ('lv', _('Latvian')),
    ('lt', _('Lithuanian')),
    ('mk', _('Macedonian')),
    ('ml', _('Malayalam')),
    ('mr', _('Marathi')),
    ('my', _('Burmese')),
    ('ne', _('Nepali')),
    ('no', _('Norwegian')),
    ('pl', _('Polish')),
    ('pt', _('Portuguese')),
    ('pa', _('Punjabi')),
    ('ro', _('Romanian')),
    ('ru', _('Russian')),
    ('sr', _('Serbian')),
    ('si', _('Sinhala')),
    ('sk', _('Slovak')),
    ('sl', _('Slovenian')),
    ('es', _('Spanish')),
    ('su', _('Sundanese')),
    ('sw', _('Swahili')),
    ('sv', _('Swedish')),
    ('ta', _('Tamil')),
    ('te', _('Telugu')),
    ('th', _('Thai')),
    ('tr', _('Turkish')),
    ('uk', _('Ukrainian')),
    ('ur', _('Urdu')),
    ('vi', _('Vietnamese')),
    ('cy', _('Welsh')),
    ('xh', _('Xhosa')),
    ('yi', _('Yiddish')),
    ('zu', _('Zulu')),
    ('gl', _('Galician')),
    ('or', _('Odia')),
    ('jv', _('Javanese')),
    ('es-mx', _('Mexican Spanish')),
    ('pt-br', _('Brazilian Portuguese')),
    ('sr-latn', _('Serbian (Latin)')),
    ('bs-latn', _('Bosnian (Latin)')),
    ('cy-gb', _('Welsh (GB)')),
    ('ml', _('Malayalam')),
    ('gu', _('Gujarati')),
    ('sw-ke', _('Swahili (Kenya)')),
    ('ta-lk', _('Tamil (Sri Lanka)')),
    ('es-ar', _('Argentinian Spanish')),
    ('it-ch', _('Swiss Italian')),
    ('fr-ca', _('Canadian French')),
    ('nl-be', _('Belgian Dutch')),
    ('pl-pl', _('Polish (Poland)')),
    ('bs-ba', _('Bosnian (Bosnia and Herzegovina)')),
    ('sr-rs', _('Serbian (Serbia)')),
    ('te', _('Telugu')),
    ('ml', _('Malayalam')),
    ('hr', _('Croatian')),
    ('lv', _('Latvian')),
    ('sl', _('Slovenian')),
    ('et', _('Estonian')),
    ('bg', _('Bulgarian')),
    ('ar-sa', _('Arabic (Saudi Arabia)')),
    ('fa-ir', _('Persian (Iran)')),
    ('iw', _('Hebrew')),
    ('pt-pt', _('Portuguese (Portugal)')),
    ('tl-ph', _('Filipino (Philippines)')),
    ('hu', _('Hungarian')),
    ('cs', _('Czech')),
    ('uk-ua', _('Ukrainian (Ukraine)')),
    ('bs-me', _('Bosnian (Montenegro)')),
    ('mr', _('Marathi')),
    ('sr', _('Serbian')),
    ('id-id', _('Indonesian (Indonesia)')),
    ('sq-al', _('Albanian (Albania)')),
    ('oc', _('Occitan')),
    ('eu', _('Basque')),
    ('si', _('Sinhala')),
    ('az', _('Azerbaijani')),
    ('bn-bd', _('Bengali (Bangladesh)')),
    ('km-kh', _('Khmer (Cambodia)')),
    ('ne-np', _('Nepali (Nepal)')),
    ('si-lk', _('Sinhala (Sri Lanka)')),
    ('tr-tr', _('Turkish')),
    ('vi-vn', _('Vietnamese')),
    ('ro-ro', _('Romanian')),
    ('zh-cn', _('Chinese (China)')),
    ('zh-tw', _('Chinese (Taiwan)')),
    ('bn-IN', _('Bengali (India)')),
    ('en-au', _('English (Australia)')),
    ('sw-tz', _('Swahili (Tanzania)')),
    ('es-cl', _('Spanish (Chile)')),
    ('fr-be', _('French (Belgium)')),
    ('nl-nl', _('Dutch (Netherlands)')),
    ('pl-pl', _('Polish (Poland)')),
    ('uk-ua', _('Ukrainian (Ukraine)')),
    ('es-co', _('Spanish (Colombia)')),
    ('pt-mo', _('Portuguese (Macau)')),
    ('en-ca', _('English (Canada)')),
]
