# Generated by Django 5.1.3 on 2024-12-01 13:13

import django.core.validators
import property.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_propertyowner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='owner',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.JSONField(default=list, validators=[property.models.validate_amenities]),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='country_code',
            field=models.CharField(max_length=2, validators=[property.models.validate_country_code]),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='images',
            field=models.JSONField(default=list, validators=[property.models.validate_image_urls]),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='review_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=2, validators=[property.models.validate_country_code]),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_abbr',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['country_code'], name='property_ac_country_3262e0_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['review_score'], name='property_ac_review__9a04cf_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['published'], name='property_ac_publish_410338_idx'),
        ),
    ]
