# Generated by Django 5.1.3 on 2024-12-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_accommodation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PropertyOwner',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
