# Generated by Django 5.1.3 on 2024-12-03 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_localizeaccommodation_property_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localizeaccommodation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.accommodation'),
        ),
    ]
