# Generated by Django 5.1.3 on 2024-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_alter_localizeaccommodation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='country_code',
            field=models.CharField(max_length=2),
        ),
    ]
